### ISSUE TITLE
kutzjm tracking GitHub Workflow

### ISSUE THREAD

**Issue by jimkutz** [jimkutz/git-class#1]
# kutzjm tracking Github Workflow
- [ ] Create branch
- [ ] Add commits on branch
- [ ] Open pull request
- [ ] Collarborate/more commits
- [ ] Merge pull requests

```
- [] Create branch
- [] Add commits on branch
- [] Open pull request
- [] Collarborate/more commits
- [] Merge pull requests
```
